spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://139.9:3306/xiaoliu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    druid:
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: 'select 1 from dual' #校验字符串
      max-active: 80
